apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deploy
  labels:
    app: resume
spec:
  selector:
    matchLabels:
      app: resume
  replicas: 1
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: 01jongmin/resume:latest
        imagePullPolicy: "Always"
