apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: 01jongminchoi@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudDNS:
          project: personal-348615
          serviceAccountSecretRef:
            name: cert-manager-key
            key: credentials.json

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-certificate
  namespace: default
spec:
  secretName: prod-tls
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - '*.jongmin.space'
  - jongmin.space
